# .gitlab-ci.yml
stages:
  - build
  - deploy

# 1️⃣ Build del sito
build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour  # mantiene la dist solo per la pipeline


# 2️⃣ Deploy su IONOS (veloce)
deploy:
  stage: deploy
  image: alpine:latest
  dependencies:
    - build
  before_script:
    - apk add --no-cache lftp unzip
  script:
    - cd dist
    - zip -r ../dist.zip ./*
    - cd ..
    - lftp -e "
        set ssl:verify-certificate no;
        open -u su86787,\$SFTP_PASS sftp://access-5019178999.webspace-host.com:22;
        put dist.zip;
        bye
      "
    - lftp -e "
        set ssl:verify-certificate no;
        open -u su86787,\$SFTP_PASS sftp://access-5019178999.webspace-host.com:22;
        ! unzip -o dist.zip -d .;
        bye
      "
